### ISSUE TITLE
Retrieve assets from url resource

### ISSUE THREAD

**Issue by trevortknguyen** [gpvigano/AsImpL#1]
Right now, AsImpL seems to be able to access models within the file system dynamically. How should it be modified in order to also access online resources.

**Comment by gpvigano** [comment]
It *should* work using the URL instead of the file path, but unfortunately I found a bug in path/URL composition. I will look to it, thanks for your suggestion.

**Comment by gpvigano** [comment]
I made a new commit to support loading from an URL, in addition to the previous support for file paths.
I tested it opening the `001_Import_SimpleTest` example scene and changing the `File Path` in `Test` game object to an URL (in future `File Path` should be changed to `UrlOrFilePath`, but I left it as is to not break existing code).
Please check if it works for you.
