### ISSUE TITLE
Incorrect Import when using .net 4.6

### ISSUE THREAD

**Issue by OlliLenz** [gpvigano/AsImpL#11]
#### Environment
> AsImpl Version:  commit a651d19
> Unity3D 2017.2.0f3

#### Steps to reproduce
When changing the scripting backend to .net 4.6, under Player Settings, the import is incorrect.

#### Expected behavior
> Standart import in the Scene 001_Import_SimpleTest

#### Current behavior
![fialure](https://user-images.githubusercontent.com/5138584/34052110-4482fafc-e1c1-11e7-8e21-87160b0d6371.PNG)

**Comment by gpvigano** [comment]
I confirm the bug, but I have no idea about the reason.
Unfortunately the current .NET 4.6 support in Unity is experimental: maybe the bug may not be in AsImpL, anyway further investigation is really needed, thanks for this issue.

**Comment by gpvigano** [comment]
I fear  the current .NET 4.6 support in Unity is **really** experimental: my Unity Editor just crashed after few tests...

**Comment by gpvigano** [comment]
The problem is still present in Unity 2017.3, vertices are warped and materials have wrong colors.
Further investigation is needed, any help or hint would be appreciated.

**Comment by gpvigano** [comment]
The problem seems to be solved with the commit 5811df0e06c20f1d4d8912c520d65add4342738b that forces the OBJ loader to use the English CultureInfo instead of the one defined by the operating system.
@OlliLenz Please confirm if it works also for you.
