### ISSUE TITLE
How to use the project on Android device?

### ISSUE THREAD

**Issue by QazyBi** [gpvigano/AsImpL#12]
I  tried to change your model to mine and edited path in xml file but there is  a mistake 
 Failed to load file:///C:/Users/Qazybek/AppData/LocalLow/DefaultCompany/New Unity/storage/emulated/0/Android/data/com.QazBi.ASMIPL/FLASHobj/FLASH.obj
how to release this part(C:/Users/Qazybek/AppData/LocalLow/DefaultCompany/New Unity)

**Comment by QazyBi** [comment]
gpvigano this is too necessary for me can you support?

**Comment by gpvigano** [comment]
The XML-based example works on Android.
I can't help you if you do not provide all the necessary information, please follow the issue template, in particular fill in the **Problems & bugs** section, also provide steps to reproduce the bug.
Thanks

**Comment by gpvigano** [comment]
Did you copy the models folder (with its sub-folders) into the persistentDataPath as stated in [EXAMPLES documentation](https://github.com/gpvigano/AsImpL/blob/master/EXAMPLES.md)?
