### ISSUE TITLE
Problems with importing own 3d models on Android device

### ISSUE THREAD

**Issue by QazyBi** [gpvigano/AsImpL#14]
shows "loading FLASH.obj then failed to load" even if I checked location of 3d model and path which I wrote in object_list_test.xml (* I have  deleted example 3d models), the line of code ( <path>/storage/emulated/0/Android/data/com.QazBi.ASIMPL/files/FLASHobj/FLASH.obj</path>)
both 3d model and "model" folders are located in  "/com.QazBi.ASIMPL" 

![2018-01-18-00-19-47 1](https://user-images.githubusercontent.com/35418229/35059548-bb6af5aa-fbe5-11e7-9671-36eebee44fe3.png)
![2018-01-18-00-19-53 1](https://user-images.githubusercontent.com/35418229/35059549-bb95869e-fbe5-11e7-8e4e-32977cb9f3a4.png)

![untitled](https://user-images.githubusercontent.com/35418229/35059420-3f8fc186-fbe5-11e7-95a3-a4deddb1089d.jpg)
![2018-01-18-00-23-17 1](https://user-images.githubusercontent.com/35418229/35059575-d59f6d16-fbe5-11e7-8148-f0f187d72e85.png)

**Comment by gpvigano** [comment]
On Android all the paths are relative to your persistentDataPath (in your case `/storage/emulated/0/Android/data/com.QazBi.ASIMPL/files/`), thus you should write paths relative to that path:

`FLASHobj/FLASH.obj`
instead of
`/storage/emulated/0/Android/data/com.QazBi.ASIMPL/files/FLASHobj/FLASH.obj`

The persistentDataPath  (`/storage/emulated/0/Android/data/com.QazBi.ASIMPL/files/`) is added by AsImpL to the relative path.

I suggest you to check if your XML file is located in the same path set in the *Config File* field of *Custom Obj Importer* component (in Unity Editor), e.g.: if you copy your XML in `/storage/emulated/0/Android/data/com.QazBi.ASIMPL/files/FLASHobj/object_list_test.xml` you must change *Config File* field to `FLASHobj/object_list_test.xml`

I hope I did understand, let me know if it works for you.

**Comment by QazyBi** [comment]
THANKS, gpvigano I did as you said and I changed 3d model AND NOW IT WORKS AWESOME.
3 more things:
*is it possible to edit the path in .xml file at runtime? I have a filebrowser(FB) for an Android devices so I can get path from FB and put it into .xml file then project will be more flexible for a user  
*how to invert uploaded file, it flipped over for 90 degrees ? 
*what to change so scale will have smaller values
I'll send finished work to you
![2018-01-18-22-19-08 1](https://user-images.githubusercontent.com/35418229/35109213-ebb824ac-fc9f-11e7-8d2a-9e20425ade02.png)

![2018-01-18-22-18-15 1](https://user-images.githubusercontent.com/35418229/35109209-ea49308e-fc9f-11e7-8e07-307f38060819.png)

**Comment by gpvigano** [comment]
If you edit the XML at run-time (e.g. you use a text editor and save your changes) you can press the *Reload* button to see your changes.
Try changing the `zUp` element to get a rotation of 90 degrees.

Anyway please note that the example you are using is just an example: a starting point for further development, it's not a ready-to-use library feature.

**Comment by QazyBi** [comment]
Hi can you suggest me how to write a code to change only <path> in xml ?

**Comment by QazyBi** [comment]
Sorry, my fault. I just want to change the value of <path> in xml file (e.g. object_list_test.xml) at runtime. for instance I get location of a file from file browser and alter existed <path> to new one. Folowing script adds new <path>, so I ask you help how can I edit current <path>? 



public void WriteToXml()
	{
		
    	string filepath = Application.dataPath + @"/models/object_list_test.xml";
		XmlDocument xmlDoc = new XmlDocument();
		
		if(File.Exists (filepath))
		{
			xmlDoc.Load(filepath);
			XmlElement elmRoot = xmlDoc.DocumentElement;
			XmlElement elmNew = xmlDoc.CreateElement("ModelImportInfo"); 
			XmlElement ModelImportInfo_PATH = xmlDoc.CreateElement("path"); 
			ModelImportInfo_PATH.InnerText = path; 			
			elmNew.AppendChild(ModelImportInfo_PATH);
			elmRoot.AppendChild(elmNew); 
			xmlDoc.Save(filepath); // save file.
		}
	}

**Comment by gpvigano** [comment]
I didn't understand what you want to edit (the XML file only, the scene, or both of them?), anyway the example provided in AsImpL is based on the `ModelImportInfo` serializable class, it has two methods `UpdateFrom()` and `ApplyTo()` to store get/set data of game objects.
If you choose another way for serialization you should implement also the synchronization with the scene.

**Comment by QazyBi** [comment]
I want to change xml file only, there is an idea to use replacechild method. Do you have any suggestions how to implement it?

**Comment by gpvigano** [comment]
Sorry, I never managed XML in that way, but I think you can find a lot of documentation in the Web, in particular at MSDN.

**Comment by QazyBi** [comment]
hi gpvigano, do know other ways to change xml element with script?

**Comment by gpvigano** [comment]
As I wrote I'm not an expert, but you can see the .NET C# documentation for this.
