### ISSUE TITLE
Ability to Attach Custom Script and custom Material on Import 

### ISSUE THREAD

**Issue by deltamish** [gpvigano/AsImpL#18]
Hey,

Loved the asset. I was wondering If theres a method to attach a script or a material when loading async. 

and also if there's going to be any optimization done using Unity Job system in the up coming releases 

Thanks

**Comment by gpvigano** [comment]
@deltamish  About your second question: unfortunately I never thought about it, I suggest to create a new issue, sharing your knowledge about Unity job system, maybe with references, so everyone can understand your proposal. I will mark it as enhancement (and I'll think about it...).

**Comment by deltamish** [comment]
Hey Thanks a lot for the solution. Its even easier and faster this way than having a for loop and regularly check for Meshes .

and sure Ill create a new issue, But I have little knowledge on the topic
