### ISSUE TITLE
Support for faces with more than 4 vertices

### ISSUE THREAD

**Issue by gpvigano** [gpvigano/AsImpL#19]
Currently AsImpL supports faces with 3 or 4 vertices.
A proper triangulation algorithm should be implemented to support faces with more vertices.

**Comment by gpvigano** [comment]
Added a very simple triangulation in the OBJ loader (see b388f439b69edd4b83dd2f4d4281240eb2fa2471), improvements can be done.

**Comment by gpvigano** [comment]
The current triangulation does not work for concave polygons, i.e. the guitar model referenced by @LucasWalters in issue #3 looks like this:
![guitar_asimpl](https://user-images.githubusercontent.com/20297129/38249576-69aca810-374c-11e8-96ca-6cf16fc4cb49.png)
(notice the wrong triangulation of the dark polygon in the centre)

**Comment by anandmulay3** [comment]
Is this inverted face issue solved? do we have a updated plugin now?
And many thanks @gpvigano, this plugin is just awesome :)

**Comment by gpvigano** [comment]
Sorry, not yet. I think there's not a trivial solution (a proper triangulation algorithm must be implemented) and I understand this is an important issue, but I haven't a solution, at the moment.
I hope someone will help us.

**Comment by gpvigano** [comment]
I finally managed to implement a decent triangulation in [my last commit](624d653cac381d0af2f3a85fa62fcf70ded1a801), starting from [Erik Nordeus's tutorial](https://www.habrador.com/tutorials/math/10-triangulation/).
Here you can see how the previous guitar model is loaded now:

![asimpl_earclipping_guitar](https://user-images.githubusercontent.com/20297129/51322117-dbe85900-1a64-11e9-8607-ad4b683d4b91.png)

I hope someone will test this new version and will give me a feedback...

**Comment by LucasWalters** [comment]
Looks good, thanks for the update!
