### ISSUE TITLE
No materials for models with more than 3 vertices per face in Unity 2017.3 (Superseded by issue #22)

### ISSUE THREAD

**Issue by gpvigano** [gpvigano/AsImpL#21]
#### Environment
AsImpL (Github master) b388f439b69edd4b83dd2f4d4281240eb2fa2471
Unity 2017.3.0f3

#### Steps to reproduce

Load a model with faces with more than 3 vertices

#### Expected behavior

Materials should be properly assigned.

#### Current behavior

A default grey material is applied (see the model by @LucasWalters in issue #3).

**Comment by gpvigano** [comment]
I made workaround to let Unity 2017.3 and above load models with more than
3 vertices per face. I disabled 32 bit indices for models with more than 3 vertices per face (168e0a39a93737d64b6ab354d7347b99c7cb70d5).
I need to further investigate this issue.
@LucasWalters: if you have any comment about this please write it here.

**Comment by LucasWalters** [comment]
The default materials being applied on the model I posted in issue #22 wasn't because of the amount of faces but due to the library not being able to find my MTL file. See my comment on issue #22.
