### ISSUE TITLE
Why Doesn't Support The Texture Photos ? Map_KD doeasn't supported

### ISSUE THREAD

**Issue by Qusai-Azzam** [gpvigano/AsImpL#25]
I have a 3D Obj Model with an *.mtl file like this:

newmtl material0
Ka 1.000000 1.000000 1.000000
Kd 1.000000 1.000000 1.000000
Ks 0.000000 0.000000 0.000000
Tr 1.000000
illum 1
Ns 0.000000
map_Kd Model.jpg

why the model doesn't appear in this app as it appears in any other 3d model viewer ?

**Comment by gpvigano** [comment]
`map_Kd` is supported, but `map_KD` is missing.
Try to add in `LoaderObj.cs` the line
`case "map_KD":`
just before the line
`case "map_Kd": // Color texture, diffuse reflectivity`
and tell me if it works.

**Comment by Qusai-Azzam** [comment]
there is also another problem, (Parsing the Float Value of (Tr) value 
then using another shader to view it, actually, I found the (Unlit/Texture ) is a good shader, so i make it the default one to deal with the models that have map_Kd texture

**Comment by gpvigano** [comment]
Choosing an unlit shader is not always the best choice, I think you can just set the flag `litDiffuse` to true in your loader options, see <https://github.com/gpvigano/AsImpL/blob/master/Assets/AsImpL/Scripts/ImportOptions.cs#L15>
