### ISSUE TITLE
Freeze with special obj

### ISSUE THREAD

**Issue by harunomura900** [gpvigano/AsImpL#32]
Editor and Webgl project is freezing with some obj.
for example:
https://poly.googleapis.com/downloads/1fahMeqZOw_/bSGSnvbEOWz/CubeRoom.obj
https://poly.googleapis.com/downloads/6XXj6DSBb08/dH3skx1SVUc/model.obj
what is solution?

**Comment by gpvigano** [comment]
I tested the links you provided and they both work (I suggest to uncheck the Z Up flag to get the correct orientation).
Did you set the **Run In Background** option in your Untity project (Player Settings/Resolution and Presentation/Resolution/Run In Background)?

**Comment by harunomura900** [comment]
Thank for your solution. it will be great help for me.
can you please let me the the good options for optimize memory on webgl?
Best

**Comment by gpvigano** [comment]
I have no experience with WebGL, I didn't understand if you already are working on optimization, anyway if you want to open an issue on that topic, maybe someone can help us.
In this case I kindly ask you to write a proper title and explain as clear as possible:
* the problem and your needs about changes in AsImpL
* your proposals for a solution
* links to documentation (and possible existing solutions)

Thank you in advance

**Comment by harunomura900** [comment]
Yes I checked again. and this repo has good performance and quality. Thank for offer this great one.

Best 
Haru N
