### ISSUE TITLE
Materials not loaded

### ISSUE THREAD

**Issue by KuraiAndras** [gpvigano/AsImpL#34]
### Problems & bugs

Materials not loaded from .mtl

#### Environment
> * version of AsImpL commit: bb0156a5bb386d5d7e19e41eede5ee78bb10b887
> * version of Unity3D v2018.3.8

#### Steps to reproduce

Load temp.obj
[temp.zip](https://github.com/gpvigano/AsImpL/files/2955894/temp.zip)

#### Expected behavior

Model is loaded with related materials

#### Current behavior

Model is loaded but with default materials, AsImpL reports that the .mtl file could not be loaded (see picture in the linked .zip folder)

**Comment by gpvigano** [comment]
Some exporters write OBJ files with absolute path for material library, even if it is in the same directory as the OBJ file.

I added a workaround to load from the same directory as the OBJ file when failed to load from absolute path.

You can find this workaround with [this commit](b191c6851dcb465c823541a214ddf8fb1d40bd76).

Let me know if this works for you.

**Comment by KuraiAndras** [comment]
Thanks, it seems to be working. The materials are loaded, and everything seems to works now.

**Comment by gpvigano** [comment]
Thank you, I close this issue. Feel free to reopen it if you discover further problems.
