### ISSUE TITLE
Dangerous load balancing

### ISSUE THREAD

**Issue by Bunny83** [gpvigano/AsImpL#42]
https://github.com/gpvigano/AsImpL/blob/698f024bdd7397f0684090882493592a5dcfcf70/Assets/AsImpL/Scripts/Loaders/LoaderObj.cs#L351-L356

This "load balancing block" that is currently at the end of the for loop should be placed at the top. Since the for loop might skip certain iterations (comments, empty lines) and we just yield every 7000th iteration we can be unlucky with the placement of comments or empty lines and might doing several multiples of 7k iterations before we hit a yield. In the worst case we would never yield.

This gives inconsistent performance results depending on the input file.

**Comment by gpvigano** [comment]
This [last commit](eb9464bed531fcbe73b39cc3b753ffb1e29f6ecc) should be a fix for this issue. Let me know if you disagree.

**Comment by Bunny83** [comment]
Yep, this should solve the issue 👍
