### ISSUE TITLE
Unexpected path normalization for ImportedModel callback after ImportModelAsync

### ISSUE THREAD

**Issue by NoTuxNoBux** [gpvigano/AsImpL#44]
#### Environment
* version of AsImpL: commit 698f024bdd7397f0684090882493592a5dcfcf70
* version of Unity3D: 2019.4.13f

#### Steps to reproduce
1. Register a callback for `ImportedModel`.
2. Call `ImportModelAsync` with a path with backslashes, such as `C:\My\Folder\model.obj`.
3. The imported path passed to the callback uses UNIX separators, i.e. `C:/My/Folder/model.obj`.

#### Expected behavior
The path is the original path that was passed to `ImportModelAsync`.

#### Current behavior
The path is [normalized internally](https://github.com/gpvigano/AsImpL/blob/master/Assets/AsImpL/Scripts/ObjectImporter.cs#L396) and then passed to the callback.

I can work around the issue by performing the same normalization in the caller, but it requires adding logic to my code that has intimate knowledge of the AsImpL internals, which could change at any time.

**Comment by gpvigano** [comment]
The last changes (04baa7bd9085c26b4e925af609cd42f190f5537c)  should solve this issue.
I think this solution should not cause side effects to other developers, anyway any further feedback is welcome.
