### ISSUE TITLE
iOS memory Usage

### ISSUE THREAD

**Issue by shyam-appymonkeys** [gpvigano/AsImpL#50]
When importing objs during runtime on an iPad, the memory doesn't get cleared after the import is completed. 

On the Unity Editor, the profiler says that the memory usage goes back down after the obj is done importing. This doesn't happen on the iPad. It just stays at a high value even after the import is done.

This is causing issues as if a user imports multiple large objects, the app crashes due to Out Of Memory.

**Comment by gpvigano** [comment]
I think this issue seems to be related to issue #43.
Sorry, I don't know a solution right now, I hope some suggestion will come from the developer community.

**Comment by gpvigano** [comment]
In [this commit](https://github.com/gpvigano/AsImpL/commit/f597eaa07ed3bdb87fc9646c7c365d0d897420e6) I implemented a solution for memory leaks (see issue https://github.com/gpvigano/AsImpL/issues/43), please let me know if this works for you. Thanks.
