### ISSUE TITLE
How do I install this ?

### ISSUE THREAD

**Issue by alexs7** [gpvigano/AsImpL#52]
Hello,

I am running Unity 2020.3.30f1 and I can't seem to install this. 

I tried installing it from github, in the package manager (git URL) but I get this error:

```
'5.5' is not a valid `unity` property value. Expected '<year>.<version>'.

Package Manager Window] Error adding package: git@github.com:gpvigano/AsImpL.git.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)
```

**Comment by gpvigano** [comment]
This question needs to be further investigated (in particular the `package.json` format), in the meanwhile you can:
- open the AsImpL project with your Unity Editor,
- let it convert the project in your Unity version,
- export the package (right click on the AsImpL folder in the project panel and select "Export Package...")
- and finally import it in your project (Assets/Import Package/Custom Package...).
The `model` folder must be copied manually if you want to test the examples.

**Comment by hadardasim** [comment]
Also had issues installing with the package manager in Unity 2021.3.2f1.
Follwing the above steps (open ... export ... import) worked for me, thanks!
