### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rezadarooei** [gpvigano/AsImpL#7]
hi dear, I have a suggestion for the new feature.we have runtime .obj model creator.if we have mouse click interaction we can use information for interaction processing

**Comment by gpvigano** [comment]
This is not a feature related to a model loader, it is more a generic utility.
On this topic you can find a lot of documentation, both in Unity documentation and forums.

Anyway you cannot use a generic word "Suggestion" as title of an issue, please write a meaningful title for your next issues, thanks.
