### ISSUE TITLE
Loading and using OBJ vertex colors

### ISSUE THREAD

**Issue by Dragate** [gpvigano/AsImpL#9]
OBJ loader could parse vertex colors, in particular if a material file is not available, and assign them to the mesh vertices so it maintains the original colors.

**Comment by gpvigano** [comment]
@Dragate: Thanks for this issue and all the hints you sent me by e-mail,
in my latest commit (a651d193f7feac2d7292d6137b0735ef124d5829) you can find a new version with
vertex colors support.
Colors are loaded from OBJ file and used only if no material library is
defined.
You already tested this with Unity 5.6.3f1 so I tested it with Unity 5.5.4f1, 2017.1.2f1, 2017.2.0f3.
Everything works fine (as far as I know).
